# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: create staticpage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        git clone https://github.com/gordonbrander/lettersmith_py
        cd lettersmith_py
        pip3 install -e .
    - name: create Webpage
      run: |
        python3 build.py      
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
  
    - name: save Page 
      run: |
        rm docs/ -r
        rm lettersmith_py/ -r
        mv public/ docs/
        git add docs/*
        git commit -m "auto"
        git push origin master

    
